apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-server.fullname" . }}
  labels:
    app: {{ include "discovery-server.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "discovery-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "discovery-server.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://{{ include "discovery-server.fullname" . }}:8761/eureka/"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
