replicaCount: 1

image:
  repository: mintr124/discovery-server
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8761

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

# Hoặc nếu cần khai báo env cho Deployment
env:
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "false"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "false"
