spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  zipkin:
    base-url: http://zipkin:9411
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
  zipkin:
    base-url: http://zipkin:9411
  eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
