replicaCount: 1

image:
  repository: mintr124/visits-service   # thay tên repo cho từng service
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
