replicaCount: 1

image:
  repository: mintr124/vets-service   # thay tên repo cho từng service
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
