apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vets-service.fullname" . }}
  labels:
    app: {{ include "vets-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vets-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "vets-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,mysql"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.eureka.serviceUrl | quote }}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.service.name | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
