apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customers-service.name" . }}
  labels:
    app: {{ include "customers-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "customers-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "customers-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,mysql"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
