apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-server.fullname" . }}
  labels:
    app: {{ include "admin-server.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
  selector:
    app: {{ include "admin-server.name" . }}
